config/routes.rb
CityUtility::Application.routes.draw do

  root :to => "docs#index"
  
  match "thecity-appkit/typography/" => "docs#typography", :as => :typography
  match "thecity-appkit/typography/index.html" => "docs#typography"
  
  match "thecity-appkit/forms/" => "docs#forms", :as => :forms
  match "thecity-appkit/forms/index.html" => "docs#forms"

  match "thecity-appkit/grid/" => "docs#grid", :as => :grid
  match "thecity-appkit/grid/index.html" => "docs#grid"

  match "thecity-appkit/buttons/" => "docs#buttons", :as => :buttons
  match "thecity-appkit/buttons/index.html" => "docs#buttons"

  match "thecity-appkit/center_stage/" => "docs#center_stage", :as => :center_stage
  match "thecity-appkit/center_stage/index.html" => "docs#center_stage"

  match "thecity-appkit/tables/" => "docs#tables", :as => :tables
  match "thecity-appkit/tables/index.html" => "docs#tables"

  match "thecity-appkit/news_feed_items/" => "docs#news_feed_items", :as => :news_feed_items
  match "thecity-appkit/news_feed_items/index.html" => "docs#news_feed_items"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/buttons.html.haml
%header.center_stage
  %h1 Buttons
  .context_bar
%h2.rule Go ahead, push our buttons
%p.grid_4 We've provided a few basic styles and guidelines for using them. In most cases, you'll need to append multiple CSS classnames to your buttons (or links that you want to look like buttons).
%p.grid_4.omega There are 2 sizes of buttons. The default size works in most cases, and for forms in the context of major user interactions. The small buttons, or mini, as we'll refer to them, work for quick actions on content.
%h4 The "btn" base class
%p
  Every button (input or href elements) gets a base class of
  = succeed "This" do
    %strong "btn".
  provides the base style that will apply to all buttons. From there, you can append additional classes, depending the action of the button.
%table.gutterbottom.with_borders.with_stripes
  %thead
    %tr
      %th Class name
      %th Use case
      %th
  %tbody
    %tr
      %td
        %pre.inline .btn.btn_go
      %td Use for positive actions (i.e. Submit, Go, Search, etc.)
      %td
        %input.btn.btn_go{:type => "submit", :value => "Submit"}/
    %tr
      %td
        %pre.inline .btn.btn_stop
      %td Use for negative actions (i.e. Delete, destroy, etc.)
      %td
        %input.btn.btn_stop{:type => "submit", :value => "Delete"}/
    %tr
      %td
        %pre.inline .btn.btn_neutral
      %td Use for neutral actions (i.e. Save Draft, Agree to terms, etc.)
      %td
        %input.btn.btn_neutral{:type => "submit", :value => "Save draft"}/
    %tr
      %td
        %pre.inline .btn.btn_cancel
      %td Use to cancel actions on a form
      %td
        %a.btn.btn_cancel{:href => "#"} Cancel
    %tr
      %td
        %pre.inline .btn.btn_animated
      %td Use to animated a button
      %td
        %a.btn.btn_animated{:href => "#"} Processing
    %tr
      %td
        %pre.inline .btn.btn_disabled
      %td Use for disabled buttons
      %td
        %a.btn.btn_disabled{:href => "#"} Submit
    %tr
      %td
        %pre.inline .btn.btn_go.btn_mini
      %td Use for quick actions on content
      %td
        %a.btn.btn_go.btn_mini{:href => "#"} Add a new item

app/views/docs/center_stage.html.haml
%header.center_stage
  %h1 This is Center Stage
  %nav.stage-tabs
    %ul
      %li
        %a{:href => "#"} Foo
      %li
        %a{:href => "#"} Bar
      %li
        %a{:href => "#"} These
      %li
        %a{:href => "#"} Are
      %li
        %a{:href => "#"} Tabs
  .context_bar
%h2.rule Center Stage is on every view in The City
%p Use it for the page title. Here's the basic usage:
%pre.prettyprint
  = preserve do
    :escaped
      <header class="center_stage">
        <h1>This is your title</h1>
        <div class="context_bar"></div>
      </header>
%p There's an empty div there for the context bar. You need it in your markup. It'll show when you need it and not when you have tabs.
%h4 Add tabs for free.
%p If your content needs tabs, Center Stage is the place to put them. Place the following markup before the context bar div:
%pre.prettyprint
  = preserve do
    :escaped
      <nav class="stage-tabs">
        <ul>
          <li><a href="#">Foo</a></li>
          <li><a href="#">Bar</a></li>
          <li><a href="#">These</a></li>
          <li><a href="#">Are</a></li>
          <li><a href="#">Tabs</a></li>
        </ul>
      </nav>
%h4.rule Full example
%pre.prettyprint
  = preserve do
    :escaped
      <header class="center_stage">
        <h1>This is your title</h1>
        <nav class="stage-tabs">
          <ul>
            <li><a href="#">Foo</a></li>
            <li><a href="#">Bar</a></li>
            <li><a href="#">These</a></li>
            <li><a href="#">Are</a></li>
            <li><a href="#">Tabs</a></li>
          </ul>
        </nav>
        <div class="context_bar"></div>
      </header>

app/views/docs/forms.html.haml
%header.center_stage
  %h1 Forms
  .context_bar
%h3.rule The 12-column form grid
%p.grid_4
  The grid for forms comes from the smart folks at
  = succeed "." do
    %a{:href => "http://formee.org"} Formee
  You can see the full
  %a{:href => "http://formee.org/demo/reference.htm"} documentation
  at their website. Simply wrap your label and input in an element(preferably an li) with the intended grid classes and Formee does the rest.
%p.grid_4.omega The classes work like this: "grid-(the number of columns you want out of 12)-12"  So, "grid-6-12" will always span exactly half of it's parent container. And "grid-4-12" will always span a third of it's container, and so on.
%pre.prettyprint.clear
  = preserve do
    :escaped
      <li class="grid-6-12">
        <label for="first_name">First name</label>
        <input type="text" name="first_name" value="" />
      </li>
%p The form styles used here assume a certain structure and order: Form, fieldset, and groups of elements. In The City we typically use unordered lists and list items to wrap our elements. Additionally, to ensure that submit buttons are placed properly, wrap them in an element with a class of "form_footer" and we'll handle the rest. Here's an example and the markup:
%h4.rule Example form
%form
  %fieldset
    %ul
      %li.grid-5-12
        %label{:for => "first_name"} First name
        %input{:name => "first_name", :type => "text", :value => ""}/
      %li.grid-5-12
        %label{:for => "last_name"} Last name
        %input{:name => "last_name", :type => "text", :value => ""}/
      %li.grid-2-12
        %label{:for => "age"} Age
        %input{:name => "age", :type => "text", :value => ""}/
      %li.grid-12-12
        %label{:for => "mj_song"} Favorite Michale Jackson song
        %input{:name => "mj_song", :type => "text", :value => ""}/
      %li.grid-6-12
        %label It makes me want to:
        %ul.formee-list
          %li.grid-6-12
            %input{:name => "jump", :type => "checkbox", :value => ""}/
            %label{:for => "jump"} Jump
          %li.grid-6-12
            %input{:name => "groove", :type => "checkbox", :value => ""}/
            %label{:for => "groove"} Groove
          %li.grid-6-12
            %input{:name => "cry", :type => "checkbox", :value => ""}/
            %label{:for => "cry"} Cry
          %li.grid-6-12
            %input{:name => "neverland", :type => "checkbox", :value => ""}/
            %label{:for => "neverland"} Go to Neverland
      %li.form_footer
        %input.btn.btn_go.right{:type => "submit", :value => "Submit"}/
        %a.btn.btn_cancel.right{:href => "#"} Cancel
%pre.prettyprint
  = preserve do
    :escaped
      <form action="" name="" id="">
        <fieldset>
          <ul>
            <li class="grid-5-12">
              <label form="first_name">First name</label>
              <input type="text" name="first_name" value=""/>
            </li>
      
            <li class="grid-5-12">
              <label form="last_name">Last name</label>
              <input type="text" name="last_name" value=""/>
            </li>
            <li class="grid-2-12">
              <label form="age">Age</label>
              <input type="text" name="age" value=""/>
            </li>
      
            
            <li class="grid-12-12">
              <label form="mj_song">Favorite Michale Jackson song</label>
              <input type="text" name="mj_song" value=""/>
            </li>
            
            <li class="grid-12-12">
              <h5>It makes you want to:</h5>
              <ul class="formee-list">
                <li class="grid-12-12">
                  <input type="checkbox" name="jump" value=""/>
                  <label form="first_name">Jump</label>
                </li>
                <li class="grid-12-12">
                  <input type="checkbox" name="groove" value=""/>
                  <label form="groove">Groove</label>
                </li>
                <li class="grid-12-12">
                  <input type="checkbox" name="cry" value=""/>
                  <label form="cry">Cry</label>
                </li>
                <li class="grid-12-12">
                  <input type="checkbox" name="neverland" value=""/>
                  <label form="neverland">Wanna go to Neverland</label>
                </li>
              </ul>
            </li>
      
            <li class="form_footer">
              <input type="submit" value="Submit" class="right btn btn_go"/>
              <a href="#" class="btn btn_cancel right">Cancel</a>
            </li>
          </ul>
        </fieldset>
      </form>
%h4.rule Form Grid Samples
%form.formee.clear
  %fieldset
    %ul
      %li.grid-6-12
        %label grid-6-12
        %input{:type => "text", :value => ""}/
      %li.grid-6-12
        %label grid-6-12
        %input{:type => "text", :value => ""}/
      %li.grid-4-12
        %label grid-4-12
        %input{:type => "text", :value => ""}/
      %li.grid-4-12
        %label grid-4-12
        %input{:type => "text", :value => ""}/
      %li.grid-4-12
        %label grid-4-12
        %input{:type => "text", :value => ""}/
      %li.grid-3-12
        %label grid-3-12
        %input{:type => "text", :value => ""}/
      %li.grid-3-12
        %label grid-3-12
        %input{:type => "text", :value => ""}/
      %li.grid-3-12
        %label grid-3-12
        %input{:type => "text", :value => ""}/
      %li.grid-3-12
        %label grid-3-12
        %input{:type => "text", :value => ""}/
      %li.grid-2-12
        %label grid-2-12
        %input{:type => "text", :value => ""}/
      %li.grid-10-12
        %label grid-10-12
        %input{:type => "text", :value => ""}/
    %ul
      %li
        %ul.formee-list
          %li.grid-3-12
            %input{:name => "foo", :type => "checkbox"}/
            %label{:for => "foo"} Chicken
          %li.grid-3-12
            %input{:name => "bar", :type => "checkbox"}/
            %label{:for => "bar"} Pulled Pork
          %li.grid-3-12
            %input{:name => "foo", :type => "checkbox"}/
            %label{:for => "foo"} Chicken
          %li.grid-3-12
            %input{:name => "bar", :type => "checkbox"}/
            %label{:for => "bar"} Pulled Pork
      %li.grid-6-12
        %h5 Choose your main dish
        %ul.formee-list
          %li.grid-6-12
            %input{:name => "food", :type => "radio"}/
            %label{:for => "foo"} Chicken
          %li.grid-6-12
            %input{:name => "food", :type => "radio"}/
            %label{:for => "bar"} Pulled Pork
      %li.form_footer
        %input.btn.btn_go.right{:type => "submit", :value => "Submit"}/

app/views/docs/grid.html.haml
%header.center_stage
  %h1 Grid
  .context_bar
%article
  %h2.rule 8 columns of fluid goodness
  .grid_4
    %p
      The fluid grid system is kindly provided by
      %a{:href => "http://960.gs"} 960.gs.
      Though the grid is fluid, The City does not support a fluid layout. However, using a fluid grid will allow for some flexibility in the future.
    %p
      The area in which your app will live is currently
      %strong 740px
      wide.
  .grid_4.omega
    %p Your columns can total up to 8, but your last column needs a class of 'omega' to keep off that right margin.
    %pre.prettyprint
      = preserve do
        :escaped
          <div class="grid_4"></div>
          <div class="grid_4 omega"></div>
.clear
  .grid_1
    %p.demo grid_1
  .grid_1
    %p.demo grid_1
  .grid_1
    %p.demo grid_1
  .grid_1
    %p.demo grid_1
  .grid_1
    %p.demo grid_1
  .grid_1
    %p.demo grid_1
  .grid_1
    %p.demo grid_1
  .grid_1.omega
    %p.demo grid_1
  .grid_2
    %p.demo grid_2
  .grid_2
    %p.demo grid_2
  .grid_2
    %p.demo grid_2
  .grid_2.omega
    %p.demo grid_2
  .grid_3
    %p.demo grid_3
  .grid_5.omega
    %p.demo grid_5
  .grid_4
    %p.demo grid_4
  .grid_4.omega
    %p.demo grid_4
  .grid_5
    %p.demo grid_5
  .grid_3.omega
    %p.demo grid_3
  .grid_6
    %p.demo grid_6
  .grid_2.omega
    %p.demo grid_2
  .grid_7
    %p.demo grid_7
  .grid_1.omega
    %p.demo grid_1
  .grid_8
    %p.demo grid_8
  %h3.rule.gutterbottom Pushing & Pulling Columns
  .push_1.grid_1.clear
    %p.demo push_1
  .push_2.grid_1.clear
    %p.demo push_2
  .push_3.grid_1.clear
    %p.demo push_3
  .push_4.grid_1.clear
    %p.demo push_4
  .push_5.grid_1.clear
    %p.demo push_5
  .push_6.grid_1.clear
    %p.demo push_6
  .push_7.grid_1.clear
    %p.demo push_7
  .pull_1.grid_1.clear.right
    %p.demo pull_1
  .pull_2.grid_1.clear.right
    %p.demo pull_2
  .pull_3.grid_1.clear.right
    %p.demo pull_3
  .pull_4.grid_1.clear.right
    %p.demo pull_4
  .pull_5.grid_1.clear.right
    %p.demo pull_5
  .pull_6.grid_1.clear.right
    %p.demo pull_6
  .pull_7.grid_1.clear.right
    %p.demo pull_7
  %h3.rule.gutterbottom.clear Prefixes & Suffixes
  .grid_6.prefix_1.suffix_1.clear
    %p.demo grid_6 prefix_1 suffix_1
  .grid_5.prefix_2.suffix_1.clear
    %p.demo grid_5 prefix_2 suffix_1
  .grid_4.prefix_3.suffix_1.clear
    %p.demo grid_4 prefix_3 suffix_1
  .grid_5.prefix_1.suffix_2.clear
    %p.demo grid_5 prefix_1 suffix_2
  .grid_4.prefix_1.suffix_3.clear
    %p.demo grid_4 prefix_1 suffix_3
  .grid_3.prefix_1.suffix_4.clear
    %p.demo grid_3 prefix_1 suffix_4

app/views/docs/index.html.haml
.container_12.clearfix
  %header.center_stage
    %h1 So you've built an app for The City.
    .context_bar
  %section
    %h2
      %strong Awesome.
    %p.intro.grid_5.suffix_3 We're happy about that. We have provided a few tools for you. We hope these tools will make it easier for you to make your app fit nicely within The City.
    %p.grid_5.suffix_3 We've put together and hosted a stylesheet for you to include in your app. This will provide you with the basic styles that we use in The City. To place it in your app, paste the following in the head of your document:
    %h4 The City Default Styles
    %pre.clear.prettyprint 
      = preserve do
        :escaped
          <link rel="stylesheet" href="http://dcascn3rg03ga.cloudfront.net/appkit/v1.3/appkit.css" />
    %h4 Javascript for HTML5 support for pre-IE 9 browsers
    %p
      This code makes new HTML5 elements block-level so that earlier versions of IE treat them correctly. Credit goes to @jon_neal and
      %a{:href => "https://github.com/aFarkas/html5shiv"} afarkas
      for this.  Full original, uncompressed source available at
      %a{:href => "https://github.com/aFarkas/html5shiv"} https://github.com/aFarkas/html5shiv
    %pre.clear.prettyprint
      = preserve do
        :escaped
          <script type="text/javascript" src="http://dcascn3rg03ga.cloudfront.net/appkit/v1.3/appkit-ie.js"></script>
    %h3 Hosting City Utilities
    %p
      If you'd rather host the City Utilities yourself, you can
      %a.zip_download_link{:href => "https://github.com/thecity/thecity-appkit/zipball/master"} download this project as a .zip file
      or
      = succeed "." do
        %a.tar_download_link{:href => "https://github.com/thecity/thecity-appkit/tarball/master"} download as a tar.gz file
      = succeed "." do
        %a#forkme_banner{:href => "https://github.com/thecity/thecity-appkit"} View this project on GitHub
    %h3.gutterbottom What's included in The City Utilities?
    .grid_4
      %h4.rule
        = link_to "Typography", typography_path
      %p Here are The City's defaults for headings, paragraphs, list and all other typographic styles. There are also a few utility classes that you may need.
    .grid_4.omega
      %h4.rule
        = link_to "Forms", forms_path
      %p
        In The City, we've leveraged the 12-column form grid from the smart folks at
        = succeed "." do
          %a{:href => "http://formee.org"} Formee
        We show you how to structure your forms so that everything lines up just right.
    .grid_4
      %h4.rule
        = link_to "Tables", tables_path
      %p You can put borders around your table cells, or you can zebra-stripe them. Or both.
    .grid_4.omega
      %h4.rule
        = link_to "Grid", grid_path
      %p
        8 columns. Fluid. It's based off of
        = succeed "." do
          %a{:href => "http://960.gs"} 960.gs
        We adapted it to fit the content area in The City. The City's content area is not fluid, but this will be future friendly.
    .grid_4
      %h4.rule
        = link_to "Buttons", buttons_path
      %p We have 4 buttons colors with the basic style. We'll explain how to use the various classnames and make your buttons look like they belong in The City.
    .grid_4.omega
      %h4.rule
        = link_to "Center Stage", center_stage_path
      %p Every page in The City has Center Stage. It's where the page header lives. You can add tabs for page nav as well.
    .grid_4
      %h4.rule
        = link_to "News Feed Items", news_feed_items_path
      %p The News Feed Item is the container in which the majority of all content is delivered in The City.

app/views/docs/news_feed_items.html.haml
%header.center_stage.clearfix
  %h1 News Feed Items
  .context_bar
%article.clearfix.clear
  %p.grid_4 The News Feed Item is a common thing in The City. News Feed Items hold lots of small bits of content, and typically link off to pages.
  %p.grid_4.omega As a result of the prominence of the News Feed Item in The City, there are several typographic styles that apply to it specifically.
  %h4.rule Example of a News Feed Item
  %article.feed_item.clearfix.gutterbottom
    .thumb
      %a{:href => "#"}
        %img{:alt => "50x50_thumb", :src => "http://placehold.it/50x50"}/
    %p.updated_badge Last updated at 9:51am
    %h1.title I'm the title of this news feed item
    .meta
      %a{:href => "#"} Tom Waits
      in
      %a{:href => "#"} Tommy's Neighborhood Group
    .feed_body
      Hey guys. I just wanted to demonstrate some copy in a News Feed Item. It's pretty rad. If I go on for days and days, it won't show here. Just a blurb. That's all. And that's all folks need to see.
    %article.clearfix.response
      .thumb
        %a{:href => "#"}
          %img{:alt => "50x50_thumb", :src => "http://placehold.it/50x50"}/
      .meta
        %a{:href => "#"} Jimbo Sneed
        in
        %a{:href => "#"} Tommy's Neighborhood Group
      .response_body
        This is a simple response body. Your items may have no responses, but that's ok. Just in case.
  %pre.prettyprint
    = preserve do
      :escaped
        <article class="feed_item clearfix">
            <div class="thumb">
              <a href="#">
                <img src="images/50x50_thumb.jpg" alt="" />
              </a>
            </div>
            <p class="updated_badge">
              Last updated at 9:51am
            </p>
            <h1 class="title">I'm the title of this news feed item</h1>
            <div class="meta"><a href="#">Tom Waits</a> in <a href="3">Tommy's Neighborhood Group</a></div>
            <div class="feed_body">
              Hey guys. I just wanted to demonstrate some copy in a News Feed Item. It's pretty rad. If
              I go on for days and days, it won't show here. Just a blurb. That's all. And that's all 
              folks need to see. 
            </div>
        
            <!-- News Feed Responses -->
        
            <article class="clearfix response">
              <div class="thumb">
                <a href="#">
                  <img src="images/50x50_thumb.jpg" alt="" />
                </a>
              </div>
              <div class="meta"><a href="#">Jimbo Sneed</a> responded on March 27</div>
              <div class="response_body">
                This is a simple response body. Your items may have no responses, but that's ok. Just 
                in case.
              </div>
            </article>
        </article>

app/views/docs/tables.html.haml
%header.center_stage
  %h1 Tables are for data!
  .context_bar
%p We've provided 2 basic ways to display your data within tables: Bordered and striped. Simply use the class names, "with_stripes" and/or "with_borders"
%h4.rule Tables with borders
%pre.prettyprint
  = preserve do
    :escaped
      <table class="with_borders">
      </table>
%table.with_borders
  %thead
    %tr
      %th User
      %th Age
      %th MJ song that makes you move
  %tbody
    %tr
      %td Dustin
      %td 31
      %td Pretty Young Thing (PYT)
    %tr
      %td Jimbo
      %td 47
      %td The Girl is Mine
%h4.rule Tables with stripes
%pre.prettyprint
  = preserve do
    :escaped
      <table class="with_stripes">
      </table>
%table.with_stripes
  %thead
    %tr
      %th User
      %th Age
      %th MJ song that makes you move
  %tbody
    %tr
      %td Dustin
      %td 31
      %td Pretty Young Thing (PYT)
    %tr
      %td Jimbo
      %td 47
      %td The Girl is Mine

app/views/docs/typography.html.haml
%header.center_stage.clearfix
  %h1 Typography
  .context_bar
%article.clearfix.clear
  %h2.rule Headings, copy and other typographic utilities
  .grid_3.gutterbottom
    %h1 This is an H1.
    %h2 This is an H2.
    %h3 This is an H3.
    %h4 This is an H4.
    %h5 This is an H5.
    %h6 This is an H6.
  .grid_5.omega
    %h4 Paragraphs
    %p Helvetica lo-fi artisan thundercats fixie shoreditch. Hoodie put a bird on it retro, next level kogi mlkshk photo booth PBR master cleanse scenester american apparel. Williamsburg typewriter yr, beard helvetica shoreditch wayfarers occupy bushwick tattooed. Put a bird on it yr williamsburg, 3 wolf moon vinyl aesthetic tattooed pork belly. Terry richardson leggings echo park whatever, helvetica pickled gentrify.
  %h4.clear Horizontal rule
  .grid_3
    %pre.prettyprint
      = preserve do
        :escaped
          <h4 class="rule">
          </h4>  
  .grid_5.omega
    %h4.rule.guttertop I'm a header with a rule
  %h4.clear Strong & Emphasis
  .grid_3
    %pre.prettyprint 
      = preserve do
        :escaped
          <strong></strong>
  .grid_5.omega.guttertop
    I'm
    %strong strong
    and you shoud check me out.
  .grid_3.clear
    %pre.prettyprint
      = preserve do
        :escaped
          <em></em>
  .grid_5.omega.guttertop
    I'm
    %em emphasized
    and you should have a look.
%article.clearfix.clear
  %h3.rule Lists
  %h4 Unordered Lists
  .grid_5
    %pre.prettyprint
      =preserve do
        :escaped
          <ul>
            <li>List items are fun</li>
            <li>But they need style</li>
            <li>Sometimes defaults are <em>just</em> fine</li>
          </ul>  
  .grid_3.omega
    %ul.guttertop
      %li List items are fun
      %li But they need style
      %li
        Sometimes defaults are
        %em just
        fine
  %h4.clear Ordered Lists
  .grid_5
    %pre.prettyprint
      = preserve do
        :escaped
          <ol>
            <li>List items are fun</li>
            <li>But they need style</li>
            <li>Sometimes defaults are <em>just</em> fine
          </ol> 
  .grid_3.omega
    %ol.guttertop
      %li List items are fun
      %li But they need style
      %li
        Sometimes defaults are
        %em just
        fine
  %h4.clear Lists with no style
  .grid_5
    %pre.prettyprint
      = preserve do
        :escaped
          <ul class="nostyle">
            <li>List items are fun</li>
            <li>But they need style</li>
            <li>Sometimes defaults are <em>just</em> fine
          </ul>
  .grid_3.omega
    %ul.nostyle.guttertop
      %li List items are fun
      %li But they need style
      %li
        Sometimes defaults are
        %em just
        fine

app/views/layouts/application.html.haml
%html
	%head
		%title The City Utilities
		= stylesheet_link_tag    "appkit", :media => "all"
		= stylesheet_link_tag    "docs", :media => "all"
		= javascript_include_tag "appkit"
		/[if IE]
			= stylesheet_link_tag    "appkit-ie", :media => "all"
			= javascript_include_tag "appkit-ie"
		= csrf_meta_tags
	%body{:onload => 'prettyPrint()'}
		%div.container
			%section.main
				%aside.sidebar
					%header.masthead
						%h1 The City Utilities
					%div.sidebar-inner
						%nav.sidenav
							%ul
								= active_link_to 'Big Picture', '/thecity-appkit/', :wrap_tag => :li
								= active_link_to 'Typography', '/thecity-appkit/typography', :wrap_tag => :li
								= active_link_to 'Forms', '/thecity-appkit/forms', :wrap_tag => :li
								= active_link_to 'Tables', '/thecity-appkit/tables', :wrap_tag => :li
								= active_link_to 'Grid', '/thecity-appkit/grid', :wrap_tag => :li
								= active_link_to 'Buttons', '/thecity-appkit/buttons', :wrap_tag => :li
								= active_link_to 'Center Stage', '/thecity-appkit/center_stage', :wrap_tag => :li
								= active_link_to 'News Feed Items', '/thecity-appkit/news_feed_items', :wrap_tag => :li
				%section.content.clearfix
					%div.content-inner
						= yield